---
abstract: 'The DuckDuckGo DuckPAN client'
author:
  - 'Torsten Raudssus <torsten@raudss.us> L<https://raudss.us/>'
build_requires:
  Dir::Self: '0.10'
  File::FindLib: '0.001001'
  File::HomeDir: '1.00'
  File::Temp: '0.22'
  File::chdir: '0.1008'
  Test::LoadAllModules: '0.021'
  Test::More: '0.98'
  Test::Script::Run: '0.05'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
  File::ShareDir::Install: '0.03'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-DuckPAN
no_index:
  directory:
    - t/
    - xt/
    - ex/
    - inc/
requires:
  App::cpanminus: '1.5007'
  CPAN::Repository: '0.007'
  Class::Load: '0.18'
  Config::INI: '0.019'
  Crypt::SSLeay: '0.58'
  Data::Printer: '0.3'
  Dist::Zilla: '4.300007'
  Dist::Zilla::Plugin::UploadToDuckPAN: '0.006'
  Email::Valid: '0.187'
  File::ShareDir::ProjectDistDir: '0.003002'
  File::Temp: '0.22'
  File::Which: '1.09'
  HTML::Parser: '3.71'
  HTML::TreeBuilder: '0'
  IO::All: '0'
  JSON: '2.59'
  LWP::Protocol::https: '0'
  LWP::Simple: '6.00'
  Module::Data: '0.006'
  Module::Pluggable: '4.8'
  Moo: '1.002000'
  MooX: '0.101'
  MooX::Cmd: '0.001'
  MooX::HasEnv: '0.003'
  MooX::Options: '3.71'
  POE: '1.354'
  Parse::CPAN::Packages::Fast: '0.04'
  Path::Class: '0.26'
  Plack: '1.0029'
  Pod::Usage: '1.63'
  Starman: '0'
  Term::UI: '0.30'
  Text::Xslate: v3.0.0
  URI: '1.60'
  WWW::DuckDuckGo: '0.015'
  version: '0.96'
resources:
  homepage: https://github.com/duckduckgo/p5-app-duckpan
  repository: git://github.com/duckduckgo/p5-app-duckpan
version: '0.139'
x_Dist_Zilla:
  perl:
    version: '5.016003'
  plugins:
    -
      class: Dist::Zilla::Plugin::ReleaseOnlyWithLatest
      name: ReleaseOnlyWithLatest
      version: '0.002'
    -
      class: Dist::Zilla::Plugin::UploadToDuckPAN
      name: UploadToDuckPAN
      version: '0.007'
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Basic/GatherDir'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Basic/PruneCruft'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Basic/ManifestSkip'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Basic/MetaYAML'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::License
      name: '@Basic/License'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Basic/Readme'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Basic/ExtraTests'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Basic/ExecDir'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Basic/ShareDir'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::MakeMaker
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: '@Basic/MakeMaker'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Basic/Manifest'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Basic/TestRelease'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Basic/ConfirmRelease'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Basic/UploadToCPAN'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      config:
        Dist::Zilla::Plugin::Git::NextVersion:
          first_version: '0.001'
          version_by_branch: '0'
          version_regexp: (?^u:^([0-9]+\.[0-9]+)$)
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: Git::NextVersion
      version: '2.022'
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: PkgVersion
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: MetaConfig
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: MetaJSON
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: PodSyntaxTests
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: GithubMeta
      version: '0.46'
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: InstallRelease
      version: '0.008'
    -
      class: Dist::Zilla::Plugin::Authority
      name: Authority
      version: '1.006'
    -
      class: Dist::Zilla::Plugin::Repository
      name: Repository
      version: '0.20'
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: '4.006'
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Name
              name: Name
              version: '4.006'
            -
              class: Pod::Weaver::Section::Version
              name: Version
              version: '4.006'
            -
              class: Pod::Weaver::Section::Region
              name: prelude
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: SYNOPSIS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: DESCRIPTION
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: OVERVIEW
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: 'EXPORTS FUNCTIONS'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: ATTRIBUTES
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: METHODS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Leftovers
              name: Leftovers
              version: '4.006'
            -
              class: Pod::Weaver::Section::Region
              name: postlude
              version: '4.006'
            -
              class: Pod::Weaver::Section::Authors
              name: Authors
              version: '4.006'
            -
              class: Pod::Weaver::Section::Legal
              name: Legal
              version: '4.006'
      name: PodWeaver
      version: '4.005'
    -
      class: Dist::Zilla::Plugin::Git::Check
      config:
        Dist::Zilla::Plugin::Git::Check:
          untracked_files: die
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - dist.ini
            - Changes
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Git/Check'
      version: '2.022'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in: []
          commit_msg: v%v%n%n%c
          time_zone: local
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - dist.ini
            - Changes
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Git/Commit'
      version: '2.022'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: ~
          signed: 0
          tag: '0.139'
          tag_format: '%v'
          tag_message: v%v
          time_zone: local
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Git/Tag'
      version: '2.022'
    -
      class: Dist::Zilla::Plugin::Git::Push
      config:
        Dist::Zilla::Plugin::Git::Push:
          push_to:
            - 'origin master'
          remotes_must_exist: 1
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Git/Push'
      version: '2.022'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: TestRequires
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: MetaNoIndex
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::ChangelogFromGit
      name: ChangelogFromGit
      version: '0.015'
    -
      class: Dist::Zilla::Plugin::TravisCI
      name: TravisCI
      version: '0.004'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '5.016'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '5.016'
x_authority: cpan:DDG
